version: "3"

services:
  client:
    build:
      context: client
    volumes:
      - ./client:/var/www/html
    ports:
      - 4542:80
    depends_on:
      - bd
      
  bd:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./bd/data:/var/lib/mysql
      - ./bd:/docker-entrypoint-initdb.d
 