version: "3"

services:
  app:
    build:
      context: app
    restart: always
    volumes:
      - ./app/php:/var/www/html
    ports:
      - 80:80
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
 